version: 0.0
os: linux
files:
  - source: spring-hello.jar
    destination: /home/ec2-user/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 300
      runas: ec2-user