apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spring-hello-rs
  labels: 
    app: spring-hello-app-rs
    type: front-end

spec: 
  template:
    metadata:
      name: spring-hello-app
      labels: 
        app: spring-hello-app
        type: front-end-app
    spec:
      containers:
      - name: spring-hello-app
        image: spring-hello
        imagePullPolicy: Never
  replicas: 3
  selector:
    matchLabels:
      app: spring-hello-app
