apiVersion: v1
kind: Service
metadata: 
  name: myapp-service  
spec: 
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  selector:
    app: spring-hello-app-pod